version: '3'
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_DATABASE: appforge
      MYSQL_ROOT_PASSWORD: 123
  appforge:
    image: com.lesofn.appforge/deploy:prod-0.1.RELEASE
    links:
      - mysqldb:mysql_host
    ports:
      - 8080:8080
    volumes:
      - ./logs:/opt/logs