server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: AppForge
    version: 1.0.0
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  datasource:
    dynamic:
      primary: user_master
      strict: false
      druid:
        initial-size: 0
        max-active: 5
        min-idle: 1
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          slow-sql-millis: 500
          log-slow-sql: true
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      encoding: UTF-8
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /v3/api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false

# 项目相关配置
app-forge:
  name: AppForge
  version: 1.0.0
  copyright-year: 2025
  captcha-type: math
  rsa-private-key: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJHg4iS1NHzIcml7iKKu3/HyZ8vSEhp48ppIKLWspm1Rai7Jb2+exIDKN6tDbGIOb1tr6zJVvDnse67DRz5JkOPbg36gwiuzCRK0YyZ8STBL3L8WmFehxxOeoAD4NumChxxpf0cp/dxe+B79o/L8/+YmqIlXIGt6tKeycISlvb5LAgMBAAECgYAJ8zsJl5szvbUMG9h8huK7N+EQ5ncZ+3ufaWJEI2QbWxfGht0v0bZZNdx+iolHK5vjMk+8bbD6icuqkSL4DSrcPYfJ21NO2gA0X3ngRBYqvVgduULQmqx6bcqbQuTKddfrenOWkFTCM6Mt6HQQZJVkwO3Lh81CZiyLwTD3HK1yZQJBAMG01uI+Nq2irEYuCnb2GPPU93IWO3gxoNdIMnINGdMgsQ8tnlfwTu8zBid9vw7aYcGIHyugECfvj9FaXHkhnK8CQQDAyonTC91Gb02Vrgv6azOf1ZbxV2LGdOxpRI+9FyZrlPXTdQ9iMtKpQVkc5YbdowVfvZcyUZ+mBb54LVLjb7clAkEAsJKD/p/vf7/1gdOePmp+vGW5WgniE+JJV3S8ZzKCA+6c99UBre+kRG8igQUjEAsJaT0IDOBPWdgKJTBVcyWsiQJBAKqd1DF5K3+dGw1fNWyOGObX8LhvPJQjf+F9crPGXBMThiZ4T3/5OGPf2ExxeNSG5EehksBOajpUlQboHZX4FR0CQQCBZEnp+S/4ZC6xdbGHDYaNXZ8jeEZQTXGrjySLILXeHuaPF8i8ghARVB8FLSmbpheVSdTEoo70j1hgF5d7BHc+"
  token:
    header: Authorization
    auto-refresh-time: 20
